data = [
    {'title': 'True',
     '1': 'external jugular vein is a reliable guide to atrial pressure.',
     '2': 'JVP is measured from supra-sternal notch',
     '3': 'N JVP rises on adbominal compression',
     '4': 'N JVP falls during inspiration',
     '5': 'JVP is more palpable than visible',
     'ans': 'ffttf'},
    {'title': 'Cardiothoracic ratio increases in',
     '1': 'neonates',
     '2': 'congestive heart failure',
     '3': 'chronic emphysema',
     '4': 'addison"s disease',
     '5': 'acromegaly',
     'ans': 'ttfft'},
    {'title': 'In auscultation of the heart, pan-systolic murmur is heard in',
     '1': 'tricuspid regurgitation',
     '2': 'mitral valve prolapse',
     '3': 'ventricular septal defect',
     '4': 'atrial septal defect',
     '5': 'aortic regurgitation',
     'ans': 'tftff'},
    {'title': 'Infective endocarditis is associated with',
     '1': 'Roth Spots',
     '2': 'Osler"s nodes',
     '3': 'cafe-au lait lesion',
     '4': 'clubbing',
     '5': 'malar flush',
     'ans': 'ttftf'},
    {'title': 'Complications of mitral stenosisi include',
     '1': 'cerebral embolism',
     '2': 'hoarseness of voice',
     '3': 'frank haemoptysis',
     '4': 'left ventricular hypertrophy',
     '5': 'pulmonary hypertension',
     'ans': 'tttft'},
]
